### ISSUE TITLE
Typescript type exports not working

### ISSUE THREAD

**Issue by Paso** [Mitsunee/modern-diacritics#8]
The package.json is missing a types declaration resulting in the error when importing
```
error TS2307: Cannot find module 'modern-diacritics' or its corresponding type declarations
```
It would be resolved by adding this to package.json
```
"types": "./dist/index.d.ts",
```

Once the package.json is fixed you get 
```
Object literal may only specify known properties, and 'removeDiacritics' does not exist in type 'LatinizeOptions'.
```
This would probably be resolved by adding this to the LatinizeOptions
```
removeDiacritics?: boolean;
```

After those fixes I get the following error 
```
node_modules/modern-diacritics/dist/index.d.ts:5:40 - error TS2307: Cannot find module './maps/types' or its corresponding type declarations.

5 export type { CharList, CharMap } from "./maps/types";
                                         ~~~~~~~~~~~~~~
Found 1 error in node_modules/modern-diacritics/dist/index.d.ts:5
```

**Comment by Mitsunee** [comment]
> Once the package.json is fixed you get
> 
> ```
> Object literal may only specify known properties, and 'removeDiacritics' does not exist in type 'LatinizeOptions'.
> ```
> 
> This would probably be resolved by adding this to the LatinizeOptions
> 
> ```
> removeDiacritics?: boolean;
> ```

This option does not exist.

> After those fixes I get the following error
> 
> ```
> node_modules/modern-diacritics/dist/index.d.ts:5:40 - error TS2307: Cannot find module './maps/types' or its corresponding type declarations.
> 
> 5 export type { CharList, CharMap } from "./maps/types";
>                                          ~~~~~~~~~~~~~~
> Found 1 error in node_modules/modern-diacritics/dist/index.d.ts:5
> ```

I'm not sure why that file is not getting included, it exists here in the code: https://github.com/Mitsunee/modern-diacritics/blob/master/src/maps/types.d.ts

**Comment by Paso** [comment]
Awesome, thank you so much!
